config/routes.rb
Rails.application.routes.draw do
	resources :hardwares
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hardware.rb
class Hardware < ApplicationRecord
	def promocao?
		valor < 100
	end

	def self.created_at
		where('created_at <= ?', Time.now).order('created_at desc')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hardwares_controller.rb
class HardwaresController < ApplicationController
	def index
		@hardwares = Hardware.created_at
	end

	def show
		@hardware = Hardware.find(params[:id])
	end

	def edit
		@hardware = Hardware.find(params[:id])
	end

	def update
		@hardware = Hardware.find(params[:id])	
		@hardware.update(hardware_params)
		redirect_to @hardware
	end

  	def new
  		@hardware = Hardware.new
  	end

  	def create
   		@hardware = Hardware.new(hardware_params)
  		@hardware.save
  		redirect_to @hardware  
  	end

  	def destroy
  		@hardware = Hardware.find(params[:id])
  		@hardware.destroy
  		redirect_to hardwares_url
  	end

  	private def hardware_params
  		params.require(:hardware).permit(:nome, :valor, :descricao, :tipo, :poster)

  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hardware_helper.rb
module HardwareHelper
end

app/helpers/hardwares_helper.rb
module HardwaresHelper
	def formata_venda(hardware)
		if hardware.promocao?
			content_tag(:strong, "Mega Promoção!")
		else
			content_tag(:strong, "Em OFF")
		end
	end

	def imagem(hardware)
		if hardware.poster.blank?
			image_tag('semImagem.jpg')
		else
			image_tag(hardware.poster)

		end	
	end
end

app/views/hardwares/_form.html.erb
<style type="text/css">
	
	.centro{
		text-align: center;
	
	}
</style>

<%= form_for(@hardware) do |f| %>
<div class="centro">
<p>
	<%= f.label :Nome %><br>
	<%= f.text_field :nome %>
</p>
<p>
	<%= f.label :Tipo %><br>
	<%= f.text_field :tipo %>
</p>
<p>
	<%= f.label :Descricão %><br>
	<%= f.text_area :descricao, cols: 20, rows:5 %>
</p>
<p>
	<%= f.label :Valor_de_venda %><br>
	<%= f.number_field :valor %>
</p>
<p>
	<%= f.label :Imagem %><br>
	<%= f.text_field :poster, placeholder: ".JPEG ou PNG"%>
</p>
<p>
	<%= f.submit %>	
	<%= link_to 'Cancelar', hardwares_path %>
</p>
</div>
<%end%>

app/views/hardwares/edit.html.erb
<h1>EDIÇÂO DE PRODUTO</h1>
<%= render 'form' %>

app/views/hardwares/index.html.erb
<article>
	<div class="container">
	

	<div class="row">
	<div class="col-lg-12">
	
	
	<style type="text/css">
	*{
		padding: 0px; margin: 0px;
	}
	.centro{
		text-align: center;
	
	}

	</style>

	<h1 class="page-header"><%= pluralize(@hardwares.size, 'HARDWARE', 'HARDWARES') %>
	<small class="nova_peca"><%= link_to "Novo Hardware", new_hardware_path%></small>	

	</h1>

	</div>
	</div>

	<% @hardwares.each do |hardware| %>
	
	<div class="row">
	<div class="col-xs-8 col-sm-6">
	<%= link_to imagem(hardware), hardware %>
	</div>
	<div class="col-xs-4 col-sm-6">
	<h3><%= link_to hardware.nome , hardware %></h3>
	<h4>Descrição:</h4>
	<p>
	<%= truncate(hardware.descricao, length:18, separator: ' ') %>
	</p>
	<h4>Tipo:</h4>
	<p>
	<%= hardware.tipo%>	
	</p>
	
	
	<h4>Valor de Venda:</h4>
	<p><%= formata_venda(hardware) %>
	<%= number_to_currency(hardware.valor) %></p>
	<br>
	</div>	
	</div>

	<% end %>
</article>

app/views/hardwares/new.html.erb
<h1>CADASTRANDO NEW PRODUTO</h1>

<%= render 'form' %>

app/views/hardwares/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<article>
<header>
<h1><%= @hardware.nome %></h1>
<%= imagem(@hardware) %>
</header>
<h3>Tipo</h3>
<p><%= @hardware.tipo %></p>
<h3>Descrição</h3>
<p><%= @hardware.descricao %></p>
<h3>Valor:</h3>
<p><%= @hardware.valor %></p>
</article>
<%= link_to "Hardwares", hardwares_path %>
<%= link_to "Editar", edit_hardware_path(@hardware) %>
<%= link_to "Deletar Produto", hardware_path(@hardware), method: :delete, data:{ confirm:"Deseja Remover Esse Produto?"} %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManutecaoAgds</title>
    <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png'), hardwares_path, class:'navbar-brand' %>
     <%= link_to 'Hardware.Net', hardwares_path, class:'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>